
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import ThemeProvider from '@/context/ThemeContext';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fintrack Pro",
  description: "Generated by dhavanik",
  authors:[{
    url:"",
    name:"dhavanik"
  }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const setInitialTheme = `
    (function() {
      try {
        const savedTheme = localStorage.getItem('theme');
        const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        const theme = savedTheme || (prefersDark ? 'dark' : 'light');
        if (theme === 'dark') {
          document.documentElement.classList.add('dark');
        } else {
          document.documentElement.classList.remove('dark');
        }
      } catch (e) {}
    })();
  `;

  

  return (
    <ThemeProvider>
      <StoreProvider>
        <html lang="en">
          <head>
            <title>Finance Invetory</title>
            <link id="favicon" rel="icon" href="/favicon-light.svg" />
            <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
          </head>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-800`}
          >
            {children}
          </body>
        </html>
      </StoreProvider>
    </ThemeProvider>
  );
}
